**Get the data**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
data = pd.read_csv("drive/MyDrive/Colab Notebooks/Regression_insurance.csv") 

In [ ]:
data.head(5)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [ ]:
data.shape

(1338, 7)

In [ ]:
data.age

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [ ]:
data['age']

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

In [ ]:
data.iloc[:,2] # 選取第3列 (python 由0開始 因此第3列是bmi)

0       27.900
1       33.770
2       33.000
3       22.705
4       28.880
         ...  
1333    30.970
1334    31.920
1335    36.850
1336    25.800
1337    29.070
Name: bmi, Length: 1338, dtype: float64

In [ ]:
data.iloc[1] # 選取實際第二行的資訊 

age                18
sex              male
bmi             33.77
children            1
smoker             no
region      southeast
charges     1725.5523
Name: 1, dtype: object

In [ ]:
data.iloc[0,5] # 選取實際第0行第五列的資訊 

'southwest'

In [ ]:
data['region'][3] # 選取region這一列實際上的第四個 

'northwest'

In [ ]:
data.iloc[1,1:3] # 選取實際第二行由二到三列的資訊 

sex     male
bmi    33.77
Name: 1, dtype: object

In [ ]:
data.describe() # 提供 csv 中的基本統計資訊 

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
data.describe().iloc[4:7,0]

25%    27.0
50%    39.0
75%    51.0
Name: age, dtype: float64

**Categorical data**

In [ ]:
data.region.astype('category').values 

['southwest', 'southeast', 'southeast', 'northwest', 'northwest', ..., 'northwest', 'northeast', 'southeast', 'southwest', 'northwest']
Length: 1338
Categories (4, object): ['northeast', 'northwest', 'southeast', 'southwest']

In [ ]:
data.region.values

array(['southwest', 'southeast', 'southeast', ..., 'southeast',
       'southwest', 'northwest'], dtype=object)

In [ ]:
c = data.region.astype('category').values
c.value_counts()

northeast    324
northwest    325
southeast    364
southwest    325
dtype: int64

In [ ]:
data.region.value_counts()

southeast    364
southwest    325
northwest    325
northeast    324
Name: region, dtype: int64

**Numpy**

In [ ]:
import numpy as np
A = np.array([2, 2, 4, 80])
np.mean(A), np.median(A)

(22.0, 3.0)

In [ ]:
B = np.array([2, 2, 4, 8])
np.var(B), np.std(B), [np.min(B), np.max(B)] 


(6.0, 2.449489742783178, [2, 8])

In [ ]:
b = np.array(([4, 5, 1], [6, 2, 7]))

In [ ]:
b

array([[4, 5, 1],
       [6, 2, 7]])

In [ ]:
b.shape

(2, 3)

In [ ]:
b.shape[0]

2

In [ ]:
b.shape[1]

3

**Feature correlation**

In [ ]:
corr_matrix = data.corr()
corr_matrix

age       bmi  children   charges
age       1.000000  0.109272  0.042469  0.299008
bmi       0.109272  1.000000  0.012759  0.198341
children  0.042469  0.012759  1.000000  0.067998
charges   0.299008  0.198341  0.067998  1.000000

**Data pre-processing (Missing data)**

In [ ]:
data_miss_value = pd.read_csv("drive/MyDrive/Colab Notebooks/Regression_insurance_missing_value.csv") 

In [ ]:
data_miss_value.head(5) 

age     sex     bmi  children smoker     region      charges
0   19  female  27.900       0.0    yes  southwest  16884.92400
1   18    male  33.770       1.0     no  southeast   1725.55230
2   28     NaN  33.000       3.0     no        NaN   4449.46200
3   33    male  22.705       0.0     no  northwest  21984.47061
4   32    male  28.880       0.0     no  northwest   3866.85520

In [ ]:
data_miss_value.shape # 原始資料大小為19行 7列

(19, 7)

In [ ]:
tmp = data_miss_value.dropna() # tmp為刪除存在nan的行
tmp.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900       0.0    yes  southwest  16884.92400
1   18    male  33.770       1.0     no  southeast   1725.55230
3   33    male  22.705       0.0     no  northwest  21984.47061
4   32    male  28.880       0.0     no  northwest   3866.85520
5   31  female  25.740       0.0     no  southeast   3756.62160

In [ ]:
tmp.shape # 刪除後剩下 13行7列

(13, 7)

In [ ]:
data_miss_value.fillna(data_miss_value.median(numeric_only=True)) # 將數值缺失的地方都補上該列的中位數

age     sex     bmi  children smoker     region      charges
0    19  female  27.900       0.0    yes  southwest  16884.92400
1    18    male  33.770       1.0     no  southeast   1725.55230
2    28     NaN  33.000       3.0     no        NaN   4449.46200
3    33    male  22.705       0.0     no  northwest  21984.47061
4    32    male  28.880       0.0     no  northwest   3866.85520
5    31  female  25.740       0.0     no  southeast   3756.62160
6    46     NaN  33.440       0.0     no  southeast   8240.58960
7    37  female  27.740       3.0     no  northwest   7281.50560
8    37    male  29.830       2.0     no  northeast   6406.41070
9    60  female  25.840       0.0     no        NaN  28923.13692
10   25    male  26.220       0.0     no  northeast   2721.32080
11   62  female  29.355       0.0    NaN  southeast  27808.72510
12   23    male  34.400       0.0     no  southwest   1826.84300
13   56  female  39.820       0.0     no  southeast  11090.71780
14   27    male  42.130       0.0    yes  southeast  39611.75770
15   19    male  24.600       1.0     no  southwest   1837.23700
16   52  female  30.780       1.0     no        NaN  10797.33620
17   23    male  23.845       0.0     no  northeast   2395.17155
18   56     NaN  40.300       0.0     no  southwest  10602.38500

In [ ]:
mode = data_miss_value.mode(dropna=True) # 統計每一列的眾數 不考慮nan
print(mode) 

     age   sex     bmi  children smoker     region      charges
0   19.0  male  22.705       0.0     no  southeast   1725.55230
1   23.0   NaN  23.845       NaN    NaN        NaN   1826.84300
2   37.0   NaN  24.600       NaN    NaN        NaN   1837.23700
3   56.0   NaN  25.740       NaN    NaN        NaN   2395.17155
4    NaN   NaN  25.840       NaN    NaN        NaN   2721.32080
5    NaN   NaN  26.220       NaN    NaN        NaN   3756.62160
6    NaN   NaN  27.740       NaN    NaN        NaN   3866.85520
7    NaN   NaN  27.900       NaN    NaN        NaN   4449.46200
8    NaN   NaN  28.880       NaN    NaN        NaN   6406.41070
9    NaN   NaN  29.830       NaN    NaN        NaN   7281.50560
10   NaN   NaN  30.780       NaN    NaN        NaN   8240.58960
11   NaN   NaN  33.000       NaN    NaN        NaN  10602.38500
12   NaN   NaN  33.440       NaN    NaN        NaN  10797.33620
13   NaN   NaN  33.770       NaN    NaN        NaN  11090.71780
14   NaN   NaN  34.400       NaN    NaN 

In [ ]:
data_miss_value.fillna(mode.iloc[0])  # 將第89行程式碼中剩下的nan 都填入 mode 第一行的內容 如此一來 data_miss_value 資料就沒有任何nan存在


age     sex     bmi  children smoker     region      charges
0    19  female  27.900       0.0    yes  southwest  16884.92400
1    18    male  33.770       1.0     no  southeast   1725.55230
2    28    male  33.000       3.0     no  southeast   4449.46200
3    33    male  22.705       0.0     no  northwest  21984.47061
4    32    male  28.880       0.0     no  northwest   3866.85520
5    31  female  25.740       0.0     no  southeast   3756.62160
6    46    male  33.440       0.0     no  southeast   8240.58960
7    37  female  27.740       3.0     no  northwest   7281.50560
8    37    male  29.830       2.0     no  northeast   6406.41070
9    60  female  25.840       0.0     no  southeast  28923.13692
10   25    male  26.220       0.0     no  northeast   2721.32080
11   62  female  22.705       0.0     no  southeast  27808.72510
12   23    male  34.400       0.0     no  southwest   1826.84300
13   56  female  39.820       0.0     no  southeast  11090.71780
14   27    male  42.130       0.0    yes  southeast  39611.75770
15   19    male  24.600       1.0     no  southwest   1837.23700
16   52  female  30.780       1.0     no  southeast  10797.33620
17   23    male  23.845       0.0     no  northeast   2395.17155
18   56    male  40.300       0.0     no  southwest  10602.38500

**Managing categorical data**

In [ ]:
import numpy as np
import pandas as pd
country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]

data = pd.DataFrame({'Country':country,'Age':age,'Salary':salary})
print(data)

     Country  Age  Salary
0     Taiwan   25   20000
1  Australia   30   32000
2    Ireland   45   59000
3  Australia   35   60000
4    Ireland   22   43000
5     Taiwan   36   52000


**LabelEncoder**

In [ ]:
from sklearn.preprocessing import LabelEncoder # import library
labelencoder = LabelEncoder() 
data_c = data['Country'] # 要編碼的類別是Country
data_c_encode = labelencoder.fit_transform(data_c) # 編碼過後的結果會回傳給 data_c_encode
print(labelencoder.classes_) # encoder 之後的類別順序 0 1 2 分別為 'Australia' 'Ireland' 'Taiwan'
print(data_c_encode)

['Australia' 'Ireland' 'Taiwan']
[2 0 1 0 1 2]


In [ ]:
data['Country'] = labelencoder.fit_transform(data_c) # 編碼過後的結果會回傳給 data中 Country這一列
print(data)

   Country  Age  Salary
0        2   25   20000
1        0   30   32000
2        1   45   59000
3        0   35   60000
4        1   22   43000
5        2   36   52000


**OneHotEncoder**

In [ ]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
data_c_1hot = encoder.fit_transform(data['Country'])
print(data_c_1hot) # onehotencoder 結果

[[0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
data_dum = pd.get_dummies(data) # get_dummies 一樣可以將類別資料轉換成數值形式的資料
pd.DataFrame(data_dum)

Country  Age  Salary
0        2   25   20000
1        0   30   32000
2        1   45   59000
3        0   35   60000
4        1   22   43000
5        2   36   52000

**Data scaling and normalization**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
data = np.array([[1., -1., 2.], 
                [2., 0., 0.], 
                [0., 1., -1.]])  
min_max_scaler = MinMaxScaler()   
new_data = min_max_scaler.fit_transform(data) 
print(new_data)   

[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]


In [ ]:
from sklearn.preprocessing import StandardScaler
data = np.array([[1., -1., 2.], 
                 [2., 0., 0.], 
                 [0., 1., -1.]])  
zscore = StandardScaler()   
new_data = zscore.fit_transform(data) 
print(new_data) 

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


**Training/ testing data split**

In [ ]:
from sklearn.model_selection import train_test_split 
data = pd.read_csv("drive/MyDrive/Colab Notebooks/Regression_insurance.csv") 
X_train, X_test, Y_train, Y_test = train_test_split(data.iloc[:, 0:6], data.iloc[:, 6], test_size=0.2, random_state = 55688)


In [ ]:
X_train.head(5)

age     sex     bmi  children smoker     region
251    63  female  32.200         2    yes  southwest
859    57    male  28.100         0     no  southwest
722    62    male  37.400         0     no  southwest
1122   53  female  36.860         3    yes  northwest
1256   51  female  36.385         3     no  northwest

In [ ]:
Y_train.head(5)

251     47305.30500
859     10965.44600
722     12979.35800
1122    46661.44240
1256    11436.73815
Name: charges, dtype: float64

In [ ]:
X_test.head(5)

age     sex     bmi  children smoker     region
1272   43    male  25.520         5     no  southeast
633    40    male  22.705         2     no  northeast
1167   29  female  24.600         2     no  southwest
1332   52  female  44.700         3     no  southwest
96     54  female  30.800         3     no  southwest

In [ ]:
Y_test.head(5)

1272    14478.33015
633      7173.35995
1167     4529.47700
1332    11411.68500
96      12105.32000
Name: charges, dtype: float64